spring.lifecycle.timeout-per-shutdown-phase: 30s

com:
  c4-soft:
    springaddons:
      security:
        issuers:
          - location: https://localhost:8443/realms/master
            authorities:
              claims:
                - realm_access.roles
                - resource_access.spring-addons-public.roles
                - resource_access.spring-addons-confidential.roles
              caze: upper
              prefix: ROLE_
        cors:
          - path: /greet
        permit-all:
        - /actuator/health/readiness
        - /actuator/health/liveness
        - /v3/api-docs
        - /v3/api-docs/**

management:
  endpoint:
    health.probes.enabled: true
  health:
    readinessstate.enabled: true
    livenessstate.enabled: true
  endpoints:
    web.exposure.include: "*"

---
spring.config.activate.on-profile: cognito
com.c4-soft.springaddons.security.issuers:
  - location: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_RzhmgLwjl
    authorities:
      claims: 
        - cognito:groups

---
spring.config.activate.on-profile: auth0
com.c4-soft.springaddons.security.issuers:
  - location: https://dev-ch4mpy.eu.auth0.com/
    authorities:
      claims:
        - roles
        - permissions