scheme: http
origins: ${scheme}://localhost:4200
keycloak-port: 8442
keycloak-issuer: ${scheme}://localhost:${keycloak-port}/realms/master
keycloak-secret: change-me
cognito-issuer: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_RzhmgLwjl
cognito-secret: change-me
auth0-issuer: https://dev-ch4mpy.eu.auth0.com/
auth0-secret: change-me

server:
  error:
    include-message: always
  ssl:
    enabled: false

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: spring-addons-confidential
          client-secret: ${keycloak-secret}
          introspection-uri: ${keycloak-issuer}/protocol/openid-connect/token/introspect

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: ${keycloak-issuer}
          username-claim: preferred_username
          authorities:
          - path: $.realm_access.roles
          - path: $.resource_access.*.roles
        resourceserver:
          cors:
          - path: /**
            allowed-origin-patterns: ${origins}
          permit-all: 
          - "/actuator/health/readiness"
          - "/actuator/health/liveness"
          - "/v3/api-docs/**"
        
logging:
  level:
    org:
      springframework:
        security: DEBUG
        
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
      
---
com:
  c4-soft:
    springaddons:
      security:
        issuers:
        - location: ${auth0-issuer}
          username-claim: $['https://c4-soft.com/user']['name']
          authorities:
          - path: $['https://c4-soft.com/user']['roles']
          - path: $.permissions
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: TyY0H7xkRMRe6lDf9F8EiNqCo8PdhICy
          client-secret: ${auth0-secret}
          introspection-uri: ${auth0-issuer}userinfo
  config:
    activate:
      on-profile: auth0
---
com:
  c4-soft:
    springaddons:
      security:
        issuers:
        - location: ${cognito-issuer}
          username-claim: $.username
          authorities:
          - path: $.cognito:groups
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: 12olioff63qklfe9nio746es9f
          client-secret: ${cognito-secret}
          introspection-uri: https://spring-addons.auth.us-west-2.amazoncognito.com/oauth2/userInfo
  config:
    activate:
      on-profile: cognito

---
scheme: https
keycloak-port: 8443

server:
  ssl:
    enabled: true

spring:
  config:
    activate:
      on-profile: ssl
